### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by noahseis** [HenrikJoreteg/mediastream-gain#6]
Hi Henrik - looking to roll this into a webrtc implementation based off of sipml5 api. 
Looks like something may be missing or typo? npm install fail.

npm install mediastream-gain
npm http GET https://registry.npmjs.org/webrtcsupport
npm http 304 https://registry.npmjs.org/webrtcsupport
npm ERR! Error: No compatible version found: webrtcsupport@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.3.1","0.3.2","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","1.0.0","1.1.0","1.2.0","1.2.1","1.2.2","1.2.3","1.2.4","1.2.5","2.0.0","1.2.6","2.0.1","1.3.0","2.1.0","1.3.1","2.1.1","1.3.2","2.1.2"]
npm ERR!     at installTargetsError (/usr/lib64/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/lib64/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/lib64/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.11.10-25-default
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "mediastream-gain"
npm ERR! cwd /srv/www/htdocs
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/www/htdocs/npm-debug.log
npm ERR! not ok code 0

**Comment by fippo** [comment]
possibly some temporary failure? npm i'ing works fine here.

the @'^ looks odd though.

**Comment by noahseis** [comment]
hmmm tried again hoping for a different result (no luck) 
Other than your base files in the project - are there other dependencies that NPM brings in?

npm install mediastream-gain
npm http GET https://registry.npmjs.org/mediastream-gain
npm http 200 https://registry.npmjs.org/mediastream-gain
npm http GET https://registry.npmjs.org/webrtcsupport
npm http 304 https://registry.npmjs.org/webrtcsupport
npm ERR! Error: No compatible version found: webrtcsupport@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.3.1","0.3.2","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","1.0.0","1.1.0","1.2.0","1.2.1","1.2.2","1.2.3","1.2.4","1.2.5","2.0.0","1.2.6","2.0.1","1.3.0","2.1.0","1.3.1","2.1.1","1.3.2","2.1.2"]
npm ERR!     at installTargetsError (/usr/lib64/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/lib64/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/lib64/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.11.10-25-default
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "mediastream-gain"
npm ERR! cwd /root
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
